# -*- coding: utf-8 -*-
"""csv_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7dx6WBLuV96VsXvg4KTEGDO_vFGjZKn
"""

pip install pandas

import pandas as pd

url_csv = '/content/CustomerOrders.csv'
df = pd.read_csv(url_csv)
display(df.head(10))

# Check missing values
df.isna()

# Check rows where any element is missing
df[df.isna().any(axis=1)]

df[df.duplicated(keep=False)]

df['OrderDate'].dtype

# Fix the dates and convert to a date datatype.
df['OrderDate'] = df['OrderDate'].replace("INVALID_DATE", "2023-07-01")
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

df.head(10)

# Fix OrderAmount.
df['OrderAmount'].replace('One Hundred Pounds', 100.0, inplace=True)
df.head(10)

import numpy as np
# Replace missing ProductID values with the default 1000 value.
df['ProductID'] = df['ProductID'].fillna(1000)
df.head(10)

# Fix Quantity.
df['Quantity'].replace('Three', 3.0, inplace=True)
df = df.dropna(subset=['Quantity'])
df.head(10)

# Fix data types.

df['Quantity'] = df['Quantity'].fillna(0).astype(float).astype(int)
df['ProductID'] = df['ProductID'].fillna(0).astype(float).astype(int).astype(str)
df['OrderAmount'] = df['OrderAmount'].fillna(0).astype(float)
df = df.astype({
    'OrderID': str,
    'CustomerID': str,
    'OrderRegion': str
})
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df.head(10)

df.info()

# Compute TotalOrderValue.
df['TotalOrderValue'] = df['OrderAmount'] * df['Quantity']
df.head(10)

# Save the cleaned file to csv.
df.to_csv('cleaned_orders.csv', index=False)